FROM python:3.7-slim

WORKDIR /app
COPY ./app/requirements.txt /app
RUN pip install -r requirements.txt
RUN pip install gunicorn
COPY ./app /app

CMD exec gunicorn --workers 1 --threads 8 --timeout 0 app:app
