name: Dockerfile Download

on:
#  schedule:
#    - cron: 0 4 * * 5
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/SharzyL/tg_searcher.git

    - name: Deploy to Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        git-config-name: GitHub Action
        git-config-email: action@github.com
        branch: tg_searcher
        folder: tg_searcher
        commit-message: Action Update
        clean: true
        clean-exclude: |
          Dockerfile
          entrypoint.sh
          redis.conf
        single-commit: false
