name: Dockerfile Download

on:
#  schedule:
#    - cron: 0 4 * * 5
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Git Clone Repository
      run: |
        git clone https://github.com/spf0209/FreeAI-Gateway.git gitclone

    - name: Deploy to Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        git-config-name: GitHub Action
        git-config-email: action@github.com
        branch: FreeAI-Gateway
        folder: gitclone
        commit-message: Action Update
        clean: true
        single-commit: false
